### PR TITLE
fix: send embed to public showcase when a project is approved

### LINKED ISSUE #44: fix: approved submissions do not send an embed to the public showcase
When a submission is approved, the according embed is not sent to the public showcase channel.

### PR DESCRIPTION
**Pull request by nullishamy**
Closes #44

### CODE REVIEW

File: src/utils/actionVotes.ts [hunk 1]
```diff
@@ -129,6 +130,22 @@ export async function approve (submission: Submission, vote: Vote, client: Proje
...
+  const successEmbed = embeds.publicShowcase(submission)
+  const { publicShowcase } = client.config.channels()
+
+  const messageRes = await Result.wrapAsync(async () => await publicShowcase.send({ embeds: [successEmbed] }))
+
+  if (messageRes.err) {
+    log.error(`Failed to send message to public showcase for submission ${submission}`)
+    log.error(messageRes.val)
+
+    // Remove the vote, it's be made in error
```
Comment (BobobUnicorn) [inline src/utils/actionVotes.ts:142]:
```suggestion
    // Remove the vote; reverting to the original state upon error.
```

File: src/utils/processVote.ts [hunk 2]
```diff
@@ -65,10 +65,11 @@ async function handleErrorResult (result: VoteModificationResult, reaction: Mess
     const reactionRes = await Result.wrapAsync(async () => await reaction.users.remove(vote.voter.id))
 
     if (reactionRes.err) {
-      log.error(`Failed to cast vote ${vote} on submission ${submission}, reason: ${result.reason}`)
-      await client.communication.reportWarning(`<@${vote.voter.id}>: Your vote could not be cast. Reason: ${result.reason}`, submission)
       return Err(reactionRes.val as Error)
     }
+
+    log.error(`Failed to cast vote ${vote} on submission ${submission}, reason: ${result.reason}`)
```
Comment (BobobUnicorn) [inline src/utils/processVote.ts:71]: should this go before the `if` statement

**Review by BobobUnicorn — CHANGES_REQUESTED** [review]

File: src/utils/processVote.ts [hunk 3]
```diff
@@ -64,11 +64,12 @@ async function handleErrorResult (result: VoteModificationResult, reaction: Mess
...
     const reactionRes = await Result.wrapAsync(async () => await reaction.users.remove(vote.voter.id))
 
+    log.error(`Failed to cast vote ${vote} on submission ${submission}, reason: ${result.reason}`)
+
     if (reactionRes.err) {
       return Err(reactionRes.val as Error)
     }
 
-    log.error(`Failed to cast vote ${vote} on submission ${submission}, reason: ${result.reason}`)
     await client.communication.reportWarning(`<@${vote.voter.id}>: Your vote could not be cast. Reason: ${result.reason}`, submission)
```
Comment (BobobUnicorn) [inline src/utils/processVote.ts:73]: move this too, yeah?

**Review by BobobUnicorn — APPROVED** [review]
