### PR TITLE
fix: improve rejection flow; add 'resubmission' reason

### LINKED ISSUE #95: Improve instant rejections
Add an instant rejection option for “resubmitted” or similar which doesn’t send a message anywhere (we should also refactor the config to make this sort of special casing easier) so that if we just need to remove a project without alerting users we can.

We also need to log the reason in the embed.

### PR DESCRIPTION
**Pull request by nullishamy**
Closes #95

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -3,6 +3,95 @@ import * as env from './utils/env'
...
+  enumValue: { name: string, value: string }
+
+  // The pretty value, for logging
+  prettyValue: string
+
+  // The templating function to create the rejection message
+  execute: (params: RejectionParams) => string
+
+  // The function to decide where to send the log
+  location: () => LogLocation
```
Comment (BobobUnicorn) [inline src/config.ts:23]: does this need to be a function? if it were an enum we could just make this a discriminated union

Comment (nullishamy) [reply src/config.ts:23]: I want the API to be flexible for future requirements, which may involve some logic etc in the predicate.
