### PR TITLE
fix: avoid "ERROR" in logs

### LINKED ISSUE #94: Reword stringified logs
Change the stringify functions to not use “ERROR” in them because our log setup interprets this as an actual error and triggers an alert.

### PR DESCRIPTION
**Pull request by nullishamy**
Closes #94

### CODE REVIEW

File: src/utils/stringify.ts [hunk 1]
```diff
@@ -29,7 +29,12 @@ export const stringify = {
       return `Submission(${submission.state}) { ${base} (id: ${submission.id}) (submissionMessageId: ${submission.submissionMessage.id}) (reviewThreadId: ${submission.reviewThread.id}) }`
     } else if (isPending(submission)) {
       // PendingSubmission
-      return `Submission(${submission.state}) { ${base} }`
+
+      // Don't log "ERROR" because coralogix will interpret this as an actual error log
+      // and dispatch an alert etc.
```
Comment (BobobUnicorn) [inline src/utils/stringify.ts:34]: can we add some detail as to when we can revert this change?
